manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: 61291c58fd3c982a884f940776b169d1fce14fc8
      import: app/west.yml
  self:
    path: config
