manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/xudongzheng
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: custom-wq-pr
      import: app/west.yml
  self:
    path: config
